[project]
name = "adventofcode2024"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adventofcode>=23.0b1",
    "mypy>=1.13.0",
    "ruff>=0.8.1",
    "z3-solver>=4.13.3.0",
]

[tool.ruff.lint]
ignore = ["E741"]
